export const PROJECTS = [
    {
        id: 0,
        title: "Tribute Page",
        subtitle: "HTML/CSS",
        description:" Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates aspernatur, numquam odit distinctio consequatur unde illum qui deleniti nisi nihil!",
        image: "assets/images/tribute.png",
        link: "https://pia007.github.io/Tribute-Page_7Magic/",
    },
    {
        id: 1,
        title: "Social Media Dashboard",
        subtitle: "HTML/CSS/JavaScript",
        description:" Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates aspernatur, numquam odit distinctio consequatur unde illum qui deleniti nisi nihil!",
        image: "assets/images/socialDash.png",
        link: "https://pia007.github.io/SocialMediaDashBoard/",
    },
    {
        id: 2,
        title: "Jubilee",
        subtitle: "HTML/CSS/JavaScript",
        description:" Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates aspernatur, numquam odit distinctio consequatur unde illum qui deleniti nisi nihil!",
        image: "assets/images/jubilee.png",
        link: "https://pia007.github.io/Jubilee/",
    },
    {
        id: 3,
        title: "JavaScript Algorithms",
        subtitle: "HTML/CSS/JavaScript",
        description:" Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates aspernatur, numquam odit distinctio consequatur unde illum qui deleniti nisi nihil!",
        image: "assets/images/jsAlgos.png",
        link: "https://www.js-algorithms.com/",
    },
    {
        id: 4,
        title: "Social Media App One",
        subtitle: "Open Source - HTML/CSS/JavaScript",
        description:" Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates aspernatur, numquam odit distinctio consequatur unde illum qui deleniti nisi nihil!",
        image: "assets/images/smaOne.png",
        link: "",
    },
    {
        id: 5,
        title: "Social Media App Two",
        subtitle: "Open Source - HTML/CSS/JavaScript",
        description:" Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates aspernatur, numquam odit distinctio consequatur unde illum qui deleniti nisi nihil!",
        image: "assets/images/smaTwo.png",
        link: "",
    },
    {
        id: 6,
        title: "Social Media App Three",
        subtitle: "Open Source - HTML/CSS/JavaScript",
        description:" Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates aspernatur, numquam odit distinctio consequatur unde illum qui deleniti nisi nihil!",
        image: "assets/images/smaThree.png",
        link: "https://github.com/Pia007/SMA-Team-3/tree/dev",
    },
    {
        id: 7,
        title: "Quote & Color Generator",
        subtitle: "HTML/CSS/JavaScript",
        description:" Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates aspernatur, numquam odit distinctio consequatur unde illum qui deleniti nisi nihil!",
        image: "assets/images/quoteGen.png",
        link: "https://pia007.github.io/RandomQuoteAndColorGenerator/",
    },
    {
        id: 8,
        title: "Sign Up Form",
        subtitle: "React",
        description:" Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates aspernatur, numquam odit distinctio consequatur unde illum qui deleniti nisi nihil!",
        image: "assets/images/signUpReact.png",
        link: "",
    },
    {
        id: 9,
        title: "Pricing Component",
        subtitle: "HTML/CSS/JavaScript", 
        description:" Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates aspernatur, numquam odit distinctio consequatur unde illum qui deleniti nisi nihil!",
        image: "assets/images/priceToggle.png",
        link: "https://pia007.github.io/PricingToggle/",
    },
    {
        id: 10,
        title: "Sample Survey",
        subtitle: "HTML/CSS",
        description:" Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates aspernatur, numquam odit distinctio consequatur unde illum qui deleniti nisi nihil!",
        image: "assets/images/sampleSurvey.png",
        link: "https://pia007.github.io/SampleSurveyForm/",
    },
    {
        id: 11,
        title: "Host a Healthcare Hero",
        subtitle: "React/Redux/Bootstraps",
        description:" Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates aspernatur, numquam odit distinctio consequatur unde illum qui deleniti nisi nihil!",
        image: "assets/images/host.png",
        link: "https://hostahealtcarehero.netlify.app/",
    }
];